arch:
  - amd64
  - ppc64le
language: java
services:
  - docker

addon:
  apt:
    packages:
      - maven

before_install:
  - docker pull alpine
script:
  - docker run -d alpine
  - docker ps -a
  - mvn --version
