arch: ppc64le
os: linux
dist: xenial
language: node_js
install:
  - echo "install stage"
script:
  - echo "hello"
before_install:
  - echo "before install phase"
before_script:
  - echo "before script phase"
after_script:
  - echo "after script phase"
after_success:
  - echo "script ran successfully!"
after_failure:
  - echo "script failed!"
